version: '3'
services:
  react-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./db.json:/app/db.json
    depends_on:
      - json-db

  json-db:
    image: "clue/json-server"  # json-server imajını kullan
    ports:
      - "3001:80"
    volumes:
      - ./db.json:/data/db.json

      deneme